version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    networks:
      - wiremock-network
    ports:
      - "8888:8080"
    volumes:
      - ./wiremock:/home/wiremock
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]

  wiremockapp:
    image: php:8.1-cli
    networks:
      - wiremock-network
    container_name: wiremockapp
    working_dir: /var/www/html
    volumes:
      - "./:/var/www/html:cached"
    ports:
      - "80:80"
    depends_on:
      - wiremock

networks:
  wiremock-network:
    driver: bridge
